
security:
  user:
    name: username
    password: password
---
server:
  port: 8013
eureka:
  instance:
    hostname: eureka-server
    instance-id: eureka-cluster-1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8014/eureka/,http://localhost:8015/eureka/
spring:
  profiles: first
---
server:
  port: 8014
eureka:
  instance:
    hostname: eureka-server
    instance-id: eureka-cluster-1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8013/eureka/,http://localhost:8015/eureka/
spring:
  profiles: second
---
server:
  port: 8015
eureka:
  instance:
    hostname: eureka-server
    instance-id: eureka-cluster-1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8013/eureka/,http://localhost:8014/eureka/
spring:
  profiles: third

# vi eureka.sh
# java -jar target/eurekacluster-0.0.1-SNAPSHOT.jar --spring.profiles.active=first&
# java -jar target/eurekacluster-0.0.1-SNAPSHOT.jar --spring.profiles.active=second&
# java -jar target/eurekacluster-0.0.1-SNAPSHOT.jar --spring.profiles.active=third
