---
security:
  user:
    name: user8013
    password: password
server:
  port: 8013
eureka:
  instance:
    hostname: eureka-server
    instance-id: eureka-cluster-1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user8014:password@localhost:8014/eureka/,http://user8015:password@localhost:8015/eureka/
spring:
  profiles: first
---
security:
  user:
    name: user8014
    password: password
server:
  port: 8014
eureka:
  instance:
    hostname: eureka-server
    instance-id: eureka-cluster-1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user8013:password@localhost:8013/eureka/,http://user8015:password@localhost:8015/eureka/
spring:
  profiles: second
---
security:
  user:
    name: user8015
    password: password
server:
  port: 8015
eureka:
  instance:
    hostname: eureka-server
    instance-id: eureka-cluster-1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user8013:password@localhost:8013/eureka/,http://user8014:password@localhost:8014/eureka/
spring:
  profiles: third


